### ISSUE TITLE
Register records to be created for data waiting to be transcribed (RAP)

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/FreeREGNonProductIssues#11] opened 2014-11-14 14:04 UTC
The information in the Register Record is used by transcribers to select work from the RAP (Registers Available Page)

**Comment by Captainkirkdawson** [comment] 2015-11-08 20:27
This is the RAP. Likely a duplicate

**Comment by edickens** [comment] 2015-11-09 09:16
No.  It is a question of whether we should get CCs now to create
    empty Register Type records in preparation for their transcription. 
    This then becomes the basis for the RAP and can say that something
    is on the image server.  It makes sure that the correct Parish and
    Register Type is set up and the year range put in.  No programming
    change needed, but documentation.  So is it now, or do we postpone
    CCs setting them up until a future version?   E
    

    On 08/11/2015 20:27, Kirk Dawson wrote:
    
    
      This is the RAP. Likely a duplicate
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PatReynolds** [comment] 2015-11-09 19:33
What version should be ascribed to this?

**Comment by sean-wood** [comment] 2016-10-12 08:43
This appears to be a duplicate of #951

**Closed** 2017-08-07 15:49 UTC
Labels: duplicate, Image, RAP, ready, Urgent
